//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace All_in_one_Study_Companion.Pages
{
    public partial class SearchLeaderboards
    {
        protected global::System.Web.UI.WebControls.TextBox SearchBox;
        protected global::System.Web.UI.WebControls.Button SearchButton;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl searchResults;
        protected global::System.Web.UI.WebControls.Repeater LeaderboardRepeater;
    }
}
