//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace All_in_one_Study_Companion.Pages
{
    public partial class WeeklySchedule
    {
        protected global::System.Web.UI.WebControls.TextBox EventTitleTextBox;
        protected global::System.Web.UI.WebControls.DropDownList DayDropDownList;
        protected global::System.Web.UI.WebControls.DropDownList StartTimeDropDownList;
        protected global::System.Web.UI.WebControls.DropDownList EndTimeDropDownList;
        protected global::System.Web.UI.WebControls.Button AddEventButton;
        protected global::System.Web.UI.WebControls.Literal WeeklyCalendarLiteral;
    }
}
