<%@ Page Title="Weekly Schedule" Language="C#" MasterPageFile="~/MasterPages/Site.Master" AutoEventWireup="true" CodeBehind="WeeklySchedule.aspx.cs" Inherits="All_in_one_Study_Companion.Pages.WeeklySchedule" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../Content/css/WeeklySchedule.css" rel="stylesheet" />
    <script src="../Content/js/WeeklySchedule.js"></script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h1>Weekly Study Schedule</h1>
    <div class="date-navigation">
        <button onclick="changeDay(-1)">Previous Day</button>
        <span id="currentDate"></span>
        <button onclick="changeDay(1)">Next Day</button>
    </div>
    <div class="table-container">
        <div class="table-wrapper" id="scheduleTable">
            <!-- The table content will be dynamically generated by JavaScript -->
        </div>
    </div>
</asp:Content>
